h.fig = figure();
set(h.fig, 'Position', get( groot, 'Screensize' ) + repelem([60 -150],1,2));

h.title = annotation(h.fig,'textbox',...
    [0.02, 0.93, 0.9, 0.05],...
    'String',{'The sui.Img control loads the correct image and draws it on an invisible axes object',...
              'By setting the MaxSize property of Img instead of Position,',...
              'the size of the image will be adjusted to fit the original image ratio'},...
    'FontSize', 10,...
    'FitBoxToText','on',...
    'EdgeColor', 'none');

h.main =  sui.StackBox('Parent', h.fig,...
    'Units', 'norm',...
    'BasePosition', [0 0.25 1 0.5],...
    'BackgroundColor', 'White', ...
    'Spacing', 5, ...
    'Padding', 15, ...
    'Align', 'center');
h.img1 = sui.Img('Units', 'pixels', 'IsCached', true, 'MaxSize', [250 200], 'Path', 'autumn.tif', 'Parent', h.main);
h.img2 = sui.Img('Units', 'pixels', 'IsCached', true, 'Position', [0 0 300 100], 'Path', 'autumn.tif', 'Parent', h.main);
h.img3 = sui.Img('Units', 'pixels', 'IsCached', true, 'MaxSize', [100 50], 'Path', 'autumn.tif', 'Parent', h.main);
h.img4 = sui.Img('Units', 'pixels', 'IsCached', true, 'MaxSize', [500 500], 'Path', 'autumn.tif', 'Parent', h.main);

h.align = uibuttongroup(h.fig, 'Position', [0.02, 0.77, 0.2, 0.1]);
h.autumn = uicontrol(h.align, 'Units', 'norm', 'Position', [0, 0.7, 1, 0.3], 'Style', 'radiobutton', 'String', 'autumn.tif', 'Callback', @(ctrl, arg) handleAlign(ctrl, arg, h));
h.saturn = uicontrol(h.align, 'Units', 'norm', 'Position', [0, 0.35, 1, 0.3], 'Style', 'radiobutton', 'String', 'saturn.png', 'Callback', @(ctrl, arg) handleAlign(ctrl, arg, h));
h.snowflakes = uicontrol(h.align, 'Units', 'norm', 'Position', [0, 0, 1, 0.3], 'Style', 'radiobutton', 'String', 'snowflakes.png', 'Callback', @(ctrl, arg) handleAlign(ctrl, arg, h));

function handleAlign(ctrl, arg, h)
    set(h.img1, 'Path', get(ctrl,'String'));
    set(h.img2, 'Path', get(ctrl,'String'));
    set(h.img3, 'Path', get(ctrl,'String'));
    set(h.img4, 'Path', get(ctrl,'String'));
end