function [root, xml] = genDOM(xml)
    if nargin < 1
        xml = ['<?xml version="1.0" encoding="utf-8"?>', newline(),... 
               '<document _type="mxml.tests.HandleModel" _version="3" id="myId">', newline(),...
               '    <child1 _type="double">123</child1>', newline(),...
               '    <child2 _type="mxml.tests.HandleModel" id="123" child1="my son">', newline(),...
               '        <child2 _type="string">The quick brown fox</child2>', newline(),...
               '        <list _type="int32">1 2 3 4 5</list>', newline(),...
               '    </child2>', newline(),...
               '    <list _type="mxml.tests.HandleModel" isList="true">', newline(),...
               '        <entry _type="mxml.tests.HandleModel">', newline(),...
               '            <id type="double">1</id>', newline(),...
               '            <child1 type="string">The quick brown fox</child1>', newline(),...
               '            <list type="int32">1 2 3 4 5</list>', newline(),...
               '        </entry>', newline(),...
               '        <entry _type="mxml.tests.HandleModel">', newline(),...
               '            <id type="double">2</id>', newline(),...
               '            <child1 type="string">Jumps over the lazy dog</child1>', newline(),...
               '            <list type="single">1 2 3 4 5; 6 7 8 9 10</list>', newline(),...
               '        </entry>', newline(),...
               '    </list>', newline(),...
               '</document>'];
    end
    
    dom = mxml.xml2dom(regexprep(xml, '>\s+<', '><'));
    root = mxml.tests.drillDOM(dom.getDocumentElement());
end

