function model = generateTestingModel()
    model = mvvm.tests.HandleModel(1);
    model.child1 = mvvm.tests.HandleModel(11,...
        mvvm.tests.HandleModel(111, 'something something', 'blah blah blha', {'The', 'Quick', 'Brown', 'Fox', 'Jumps', 'Over', 'The', 'Lazy', 'Dog'}),...
        1:10,...
        [mvvm.tests.HandleModel(101, 'blah', 100), mvvm.tests.HandleModel(101, 'blah blah', 200), mvvm.tests.HandleModel(101, 'blah blah blah', 300)]);
    model.child2 = mvvm.tests.HandleModel(12,...
        mvvm.tests.ValueModel(121,...
            mvvm.tests.HandleModel(1211, 4:13, (11:20)'),...
            'blah',...
            struct('name', {'Bill' 'Bob' 'Barney'}, 'id', {1 2 3})),...
        1:100,...
        magic(10));
    model.list = readtable('Patients.dat');
    model.list.Properties.RowNames = model.list.LastName;
end