classdef ModelBindingTests < matlab.unittest.TestCase & mvvm.providers.IModelProvider

    properties
        model;
        gui;
    end
    
    methods
        
        function model = getModel(this)
            model = this.model;
        end
        
        function setModel(this, model)
            this.model = model;
            
        end
    end
    
    methods (TestMethodSetup)
        function createGUI(testCase)
            testCase.gui.fig = figure(99);
            testCase.gui.txt = uicontrol(testCase.gui.fig, 'style', 'text');
        end
        function createModel(testCase)
            testCase.model = mvvm.tests.generateTestingModel();
        end
    end
    
    methods (TestMethodTeardown)
        function terminateGui(testCase)
            close(testCase.gui.fig);
        end
    end
    
    methods (Test)
        function bindAllHandlesPath(testCase)
            bnd = mvvm.Binder('child1.child1.child1', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child1.child1.child1, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child1.child1.child1, ...
                testCase.gui.txt.String);
            
            testCase.model.child1.child1.child1 = ':)';
            
            assert(...
                isequal(':)', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child1.child1.child1, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'it works';
            
            assert(...
                isequal('it works', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle_changeModel_child2(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2 = mvvm.tests.HandleModel(3,...
                mvvm.tests.ValueModel(31, [],...
                    'The quick bron fox'));
            
            assert(...
                isequal('The quick bron fox', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle_changeModel_child2_child1(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1 = mvvm.tests.ValueModel(31, 'Jumps over the lazy dog',...
                    'The quick bron fox');
            
            assert(...
                isequal('The quick bron fox', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 

        function bindHandleValueHandle_changeModel_child2_child1_child2(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle_subsequentModelUpdates_topDown(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2 = mvvm.tests.HandleModel(3,...
                mvvm.tests.ValueModel(31, [],...
                    'The quick bron fox2'));
            
            assert(...
                isequal('The quick bron fox2', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle_subsequentModelUpdates_bottomUp(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            testCase.model.child2 = mvvm.tests.HandleModel(3,...
                mvvm.tests.ValueModel(31, [],...
                    'The quick bron fox2'));
            
            assert(...
                isequal('The quick bron fox2', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        
        function bindHandleValueHandle_changeModel_child2Child1Child2_several(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'The quick brown fox';
            
            assert(...
                isequal('The quick brown fox', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            testCase.model.child2.child1.child2 = 'Again and again';
            
            assert(...
                isequal('Again and again', testCase.gui.txt.String), ...
                'Data binding on model change failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
        end 
        
        function bindHandleValueHandle_stopObserving(testCase)
            bnd = mvvm.Binder('child2.child1.child2', testCase.gui.txt, 'String', 'Event', 'Callback', 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child2.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            delete(bnd);
            
            testCase.model.child2.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                ~isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change should have failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
        end 
        
        function binderIsKeptAliveByBindingManager(testCase)
            bm = mvvm.tests.TestBindingManager();
            
            % modelPath, control, property, event, modelProvider
            binder = mvvm.Binder('child1.child1.child2', testCase.gui.txt, 'String', 'BindingManager', bm, 'ModelProvider', testCase);
            
            assert(...
                isequal(testCase.model.child1.child1.child2, testCase.gui.txt.String), ...
                'Initial data binding failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child2.child1.child2, ...
                testCase.gui.txt.String);
            
            % clearing the binders last reference does not delete it
            % because it is kept alive by the binding manager
            binder = [];
            
            testCase.model.child1.child1.child2 = 'Jumps over the lazy dog';
            
            assert(...
                isequal('Jumps over the lazy dog', testCase.gui.txt.String), ...
                'Data binding on model change should have failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child1.child1.child2, ...
                testCase.gui.txt.String);
        
            % delete binding manager to delete the binder
            delete(bm);
            
        end
        
        function binderAfterRemovingFromManagerNotKeptAlive(testCase)
            bm = mvvm.tests.TestBindingManager();
            
            % modelPath, control, property, event, modelProvider
            binder = mvvm.Binder('child1.child1.child2', testCase.gui.txt, 'String', 'BindingManager', bm, 'ModelProvider', testCase);
            
            % this should delete the binder
            bm.clearBinder(binder);
            
            testCase.model.child1.child1.child2 = 'JUMPS OVER THE LAZY DOG';
            
            assert(...
                ~isequal('JUMPS OVER THE LAZY DOG', testCase.gui.txt.String), ...
                'Data binding on model change should have failed. Model Value: ''%s'', TextBox Value: ''%s''', ...
                testCase.model.child1.child1.child2, ...
                testCase.gui.txt.String);
        end
    end

end