classdef EnumCtor < mfc.IMCtor
    %ENUMCTOR Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        Ctor mfc.IMCtor = mfc.MCtor.empty();
    end
    
    methods
        function this = EnumCtor(ctor)
            if isa(ctor, 'mfc.IMCtor')
                this.Ctor = ctor;
            else
                this.Ctor = mfc.MCtor(ctor);
            end
        end
        
        % constructs an instance of a class
        function obj = build(this, extractor)
            if nargin ~= 2
                throw(MException('mfc:EnumCtor:InvalidCtorInput', 'mfc.EnumCtor accepts only one input variable'));
            end
            
            value = extractor.get();
            
            if ischar(value) || isStringScalar(value)
                if any(regexp(value, '^\-?[\d,]+\.?[\d,]*$'))
                    value = str2double(value);
                end
            end
            obj = this.Ctor.build(value);
        end
        
        % Returns the type name generated by this IMCtor
        function type = getTypeName(this)
            type = this.Ctor.getTypeName();
        end
    end
end

