classdef (Abstract) IMCtor < handle & matlab.mixin.Heterogeneous
    methods (Abstract)
        % constructs an instance of a class
        obj = build(this, varargin);
        
        % Returns the type name generated by this IMCtor
        type = getTypeName(this);
    end
end

